### ISSUE TITLE
Chosen Dependency issue

### ISSUE THREAD

**Issue by chriskozlowski** [chenglou/react-chosen#14]
It seems that there is no release that satisfies ~1.1.0 anymore in the bower-friendly chosen repo

**Comment by kharandziuk** [comment]
just for reference. Console output looks like this:
```
bower install react-chosen --save
bower react-chosen#*        not-cached git://github.com/chenglou/react-chosen.git#*
bower react-chosen#*           resolve git://github.com/chenglou/react-chosen.git#*
bower react-chosen#*          download https://github.com/chenglou/react-chosen/archive/v0.3.7.tar.gz
bower react-chosen#*           extract archive.tar.gz
bower react-chosen#*          resolved git://github.com/chenglou/react-chosen.git#0.3.7
bower react#~0.12.1         not-cached git://github.com/facebook/react-bower.git#~0.12.1
bower react#~0.12.1            resolve git://github.com/facebook/react-bower.git#~0.12.1
bower chosen#~1.1.0         not-cached git://github.com/harvesthq/bower-chosen.git#~1.1.0
bower chosen#~1.1.0            resolve git://github.com/harvesthq/bower-chosen.git#~1.1.0
bower react#~0.12.1           download https://github.com/facebook/react-bower/archive/v0.12.2.tar.gz
bower react#~0.12.1            extract archive.tar.gz
bower react#~0.12.1           resolved git://github.com/facebook/react-bower.git#0.12.2
bower chosen#~1.1.0       ENORESTARGET No tag found that was able to satisfy ~1.1.0

Additional error details:
Available versions: 1.4.2, 1.4.1
```

Possible workaround in this case to install package with command:
`bower install git@github.com:chenglou/react-chosen.git#master`

**Comment by neemzy** [comment]
Same issue here, your `bower.json` looks correct but it seems an outdated version is still on the Bower repositories. What could be done?

**Comment by nicolasiensen** [comment]
+1 does anyone forked this repo to fix it?

**Comment by kharandziuk** [comment]
@nicolasiensen I provided a workaround. Doesn't it work for you?

**Comment by nicolasiensen** [comment]
@kharandziuk it seems that bower doesn't accept ```git@github.com:chenglou/react-chosen.git#master``` as parameter.

I ended up doing ```bower install https://raw.githubusercontent.com/chenglou/react-chosen/master/react-chosen.js```

**Comment by kharandziuk** [comment]
strange, it works for me
```
$> bower install git@github.com:chenglou/react-chosen.git#master
bower react-chosen#master   not-cached git@github.com:chenglou/react-chosen.git#master
bower react-chosen#master      resolve git@github.com:chenglou/react-chosen.git#master
```

**Comment by nicolasiensen** [comment]
Ok, I'm using [iTerm](https://www.iterm2.com/) and for some reason I had to double quoted the Github path: ```bower install "git@github.com:chenglou/react-chosen.git#master"```, it's working now thanks!

**Comment by pixeldrew** [comment]
Can we get a version bump for this? Just to fix the bower issue.

**Comment by chenglou** [comment]
Just bumping the version? Done. Tell me if it doesn't work

**Comment by neemzy** [comment]
Lookin' good, thanks!
