### ISSUE TITLE
Deprecated 

### ISSUE THREAD

**Issue by rolandsusans** [chenglou/react-chosen#21]
According to :       https://github.com/chenglou/react-chosen/issues/19

is this project deprecated and will be no more supported by its author ?

**Comment by chenglou** [comment]
Yes, haven't put up the actual note yet, but there's really no reason to use this library anymore now that we've got much better react-only solutions two years later =)

**Comment by PetrGlad** [comment]
@chenglou, you mentioned other solutions, what do you use instead, for example?

**Comment by chenglou** [comment]
https://github.com/JedWatson/react-select

**Comment by PetrGlad** [comment]
Thanks

**Comment by neemzy** [comment]
Could you put up a big warning at the top of the README explicitly stating this, to avoid people wasting time? Thanks!

**Comment by chenglou** [comment]
@neemzy done! Sorry for the delay.

**Comment by neemzy** [comment]
No worries! Cheers :)
